experiment_dir: logs/bsds300/imputation/sampling_u50_wholedataset_storelast/vae_marginal_vae_baseline/seed_m{}_d20220118/lightning_logs/version_{}/

seed_everything: 20220118
data:
  setup_seed: 20220118
  dataset: bsds300
  use_test_instead_val: False
  # num_first_datapoints_test: 3000
  batch_size: 512
  missingness: 'uniform'
  total_miss_train: 0.0
  total_miss_val: 0.0
  total_miss_test: 0.5
  filter_fully_missing_test: True
  data_root: ./data

# To generate imputations from
vae_path: logs/bsds300/imputation/vae/seed_m20220118_d20220118/lightning_logs/version_{}/checkpoints/
load_best_vae: True
# use_marginal_vae_samples_instead_of_imputations: True

batch_size: 512
num_imps: 5

