experiment_dir: logs/omniglot28x28_bin/imputation/q50/vae_convresnet2_marginal_vae_baseline/seed_m{}_d20220118/lightning_logs/version_{}/

data:
  setup_seed: 20220118
  dataset: 'omniglot28x28_fbin'
  use_test_instead_val: False
  batch_size: 200
  missingness: 'quadrants'
  img_dims:
   - 28
   - 28
  total_miss_train: 0.0
  total_miss_val: 0.0
  total_miss_test: 0.50
  data_root: ./data

# To generate imputations from
vae_path: logs/omniglot28x28_bin/imputation/vae_convresnet2/seed_m20220118_d20220118/lightning_logs/version_{}/checkpoints/epoch=2999-step=411000.ckpt

batch_size: 200
num_imps: 5

