experiment_dir: logs/uci_miniboone/imputation/eval_sampling_u50/vae2_no_kl_sched_drop05_marginal_vae_baseline/seed_m20220118_d20220118/lightning_logs/version_{}/
experiment_path: logs/uci_miniboone/imputation/sampling_u50/vae2_no_kl_sched_drop05_k5_pseudo_gibbs/seed_m20220118_d20220118/lightning_logs/version_{}/

seed_everything: 20220118
data:
  setup_seed: 20220118
  dataset: uci_miniboone
  use_test_instead_val: False
  num_first_datapoints_test: 3000
  batch_size: 512
  missingness: 'uniform'
  total_miss_train: 0.0
  total_miss_val: 0.0
  total_miss_test: 0.5
  filter_fully_missing_test: True
  data_root: ./data

# To generate imputations from
vae_path: logs/uci_miniboone/imputation/vae2_no_kl_sched_drop05/seed_m20220118_d20220118/lightning_logs/version_{}/checkpoints/
load_best_vae: True
use_marginal_vae_samples_instead_of_imputations: True

batch_size: 128
last_n_imputations: 2900
every_nth_step: 1

process_irwg_finalresample: False

# cr_ci_level: 0.95
quantile_levels: [0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  , 0.225,
                  0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  , 0.425, 0.45 ,
                  0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  , 0.625, 0.65 , 0.675,
                  0.7  , 0.725, 0.75 , 0.775, 0.8  , 0.825, 0.85 , 0.875, 0.9  ,
                  0.925, 0.95 , 0.975]
