experiment_dir: logs/uci_gas/imputation/eval_sampling_u50_fid_nn_imps/vae_no_kl_sched_k5_mwg_with_ps_warmup/seed_m20220118_d20220118/lightning_logs/version_{}/
experiment_path: logs/uci_gas/imputation/sampling_u50/vae_no_kl_sched_k5_mwg_with_ps_warmup/seed_m20220118_d20220118/lightning_logs/version_{}/
nn_imp_path: logs/uci_gas/imputation/find_train_nn/uci_gas/seed_m20220118_d20220118/lightning_logs/version_0/

seed_everything: 20220118
data:
  setup_seed: 20220118
  dataset: uci_gas
  use_test_instead_val: False
  num_first_datapoints_test: 3000
  batch_size: 512
  missingness: 'uniform'
  total_miss_train: 0.0
  total_miss_val: 0.0
  total_miss_test: 0.5
  filter_fully_missing_test: True
  data_root: ./data

# To generate imputations from
vae_path: logs/uci_gas/imputation/vae_no_kl_sched/seed_m20220118_d20220118/lightning_logs/version_{}/checkpoints/
load_best_vae: True
# use_marginal_vae_samples_instead_of_imputations: True

use_N_nn_imps: 100

batch_size: 512
last_n_imputations: 2900
every_nth_step: 1

process_irwg_finalresample: False

